class KioskLocalizations {
  final String langCode;

  KioskLocalizations(this.langCode);

  static const Map<String, String> languageNames = {
    'ta': 'தமிழ்',
    'te': 'తెలుగు',
    'ml': 'മലയാളം',
    'hi': 'हिन्दी',
    'kn': 'ಕನ್ನಡ',
    'en': 'English',
  };

  static const Map<String, String> languageEnglishNames = {
    'ta': 'Tamil',
    'te': 'Telugu',
    'ml': 'Malayalam',
    'hi': 'Hindi',
    'kn': 'Kannada',
    'en': 'English',
  };

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'SarVani',
      'chooseLanguage': 'Choose your language',
      'touchToBegin': 'Touch your language to begin',
      'askQuestion': 'Ask your question',
      'speakNaturally': 'Speak naturally in your selected language. You do not need legal terms.',
      'tapToSpeak': 'TAP TO SPEAK',
      'touchMicOrSpeak': 'Touch Microphone or speak naturally',
      'listening': 'Listening…',
      'stop': 'Stop',
      'sampleQuestionsTitle': 'Sample Questions:',
      'understandingQuestion': 'Understanding your question...',
      'findingInformation': 'Finding the right information...',
      'backendRoute': 'Backend Route:',
      'yourAnswer': 'Your Answer',
      'repeat': 'Hear Again',
      'stopAudio': 'Pause',
      'askAnother': 'Ask Another Question',
      'showDocuments': 'Required Documents',
      'actionNextStepLabel': 'Next Steps',
      'getHumanHelp': 'Help / Complaint Info',
      'endSession': 'Exit',
      'reset': 'Reset',
      'q1_title': 'Which documents are required for KCC card?',
      'q1_sub': 'What documents are required for KCC loan application?',
      'q2_title': 'What is my KCC loan balance?',
      'q2_sub': 'Check KCC loan account balance & due date',
      'q3_title': 'How to file a complaint in PACS society?',
      'q3_sub': 'How to register a grievance with PACS Secretary?',
      'q_member_rights': 'What are my rights as a cooperative member?',
      'a_member_rights': 'As a registered cooperative member, you have the statutory right to inspect society books, audit reports, list of members, and annual financial statements without restriction.',
      'q_crop_loan_docs': 'Which documents are needed for PACS crop loan application?',
      'a_crop_loan_docs': 'To apply for PACS short-term crop loan or input subsidy, members must provide landholding record (Pattadar Passbook), Aadhaar card, PACS member passbook, and Form-A application.',
      'q_grievance': 'How can I complain if my cooperative does not provide my records?',
      'a_grievance': 'First, submit a written request to the PACS Secretary. If unresolved after 15 days, file a formal complaint to the District Deputy Registrar of Cooperative Societies.',
      'q_crop_insurance': 'What is the claim process and timeline for crop insurance?',
      'a_crop_insurance': 'Crop loss due to natural calamities must be reported to the PACS Secretary or Crop Insurance Helpline within 72 hours of damage for joint field inspection.',
      'documentsChecklistTitle': 'Required Documents',
      'doc1': '1. Land Record Document (Patta / Adangal / Chitta)',
      'doc2': '2. Aadhaar Card Copy',
      'doc3': '3. PACS Membership Passbook',
      'doc4': '4. 2 Passport Photographs & Loan Application Form',
      'step1': 'Step 1: Visit your local PACS Secretary during working hours (9 AM - 5 PM).',
      'step2': 'Step 2: Submit filled application form along with verified documents.',
      'step3': 'Step 3: Collect your stamped acknowledgement receipt for tracking.',
      'help1': 'PACS Secretary Helpline: 1800-425-1090',
      'help2': 'District Cooperative Registrar Office: Block B, Civil Station',
      'help3': 'Grievance Period: 15-day mandatory resolution timeframe.',
    },
    'ta': {
      'appName': 'SarVani',
      'chooseLanguage': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'touchToBegin': 'தொடங்க மொழியைத் தொடவும்',
      'askQuestion': 'உங்கள் கேள்வியைக் கேளுங்கள்',
      'speakNaturally': 'உங்கள் தாய்மொழியில் இயல்பாகப் பேசுங்கள். சட்டச் சொற்கள் தேவையில்லை.',
      'tapToSpeak': 'பேசத் தொடங்குங்கள்',
      'touchMicOrSpeak': 'ஒலிவாங்கியைத் தொட்டு இயல்பாகப் பேசுங்கள்',
      'listening': 'கேட்கிறது…',
      'stop': 'நிறுத்து',
      'sampleQuestionsTitle': 'மாதிரி கேள்விகள்:',
      'understandingQuestion': 'உங்கள் கேள்வியைப் புரிந்து கொள்கிறது...',
      'findingInformation': 'சரியான தகவலைத் தேடுகிறது...',
      'backendRoute': 'சேவை வழி:',
      'yourAnswer': 'உங்கள் பதில்',
      'repeat': 'மீண்டும் சொல்',
      'stopAudio': 'நிறுத்து',
      'askAnother': 'மற்றொரு கேள்வி கேள்',
      'showDocuments': 'தேவையான ஆவணங்கள்',
      'actionNextStepLabel': 'அடுத்த கட்ட நடவடிக்கைகள்',
      'getHumanHelp': 'உதவி / புகார் விவரம்',
      'endSession': 'அமர்வை முடி',
      'reset': 'மீட்டமை',
      'q1_title': 'கேசிசி கார்டுக்கு என்ன ஆவணங்கள் வேண்டும்?',
      'q1_sub': 'கேசிசி கடன் விண்ணப்பத்திற்குத் தேவையான ஆவணங்கள் விவரம்',
      'q2_title': 'என் கேசிசி கடன் இருப்பு எவ்வளவு?',
      'q2_sub': 'கடன் கணக்கு இருப்பு மற்றும் திருப்பிச் செலுத்தும் தேதி சரிபார்',
      'q3_title': 'சங்கத்தில் புகார் எப்படி செய்வது?',
      'q3_sub': 'கூட்டுறவு சங்க செயலாளரிடம் புகார் அளிக்கும் முறை',
      'q_member_rights': 'கூட்டுறவு சங்க உறுப்பினராக எனக்கு என்ன உரிமைகள் உள்ளன?',
      'a_member_rights': 'பதிவுசெய்த கூட்டுறவு உறுப்பினராக, சங்கத்தின் கணக்கு புத்தகங்கள், தணிக்கை அறிக்கைகள், உறுப்பினர் பட்டியல் மற்றும் ஆண்டு நிதிநிலை அறிக்கைகளைப் பார்வையிட உங்களுக்கு முழு சட்டப்பூர்வ உரிமை உண்டு.',
      'q_crop_loan_docs': 'கூட்டுறவு பயிர் கடனுக்கு என்ன ஆவணங்கள் வேண்டும்?',
      'a_crop_loan_docs': 'கூட்டுறவு சங்கத்தில் பயிர் கடன் அல்லது கேசிசி பெற நில உரிமை ஆவணம் (பட்டா/சிட்டா), ஆதார் கார்டு, சங்க உறுப்பினர் பாஸ்புக் மற்றும் விண்ணப்ப படிவம் சமர்ப்பிக்க வேண்டும்.',
      'q_grievance': 'கூட்டுறவு சங்கம் ஆவணங்களை வழங்கவில்லை என்றால் எப்படி புகார் செய்வது?',
      'a_grievance': 'முதலில் சங்க செயலாளரிடம் எழுத்துப்பூர்வமாக விண்ணப்பித்து ஒப்புதல் சீட்டு பெறவும். 15 நாட்களில் தீர்வு இல்லையெனில் மாவட்ட கூட்டுறவு துணை பதிவாளரிடம் புகார் அளிக்கலாம்.',
      'q_crop_insurance': 'பயிர் காப்பீட்டு உரிமை கோருவதற்கான காலக்கெடு என்ன?',
      'a_crop_insurance': 'இயற்கை சீற்றத்தால் பயிர் சேதம் அடைந்தால் 72 மணி நேரத்திற்குள் சங்க செயலாளருக்கோ காப்பீட்டு உதவி மையத்திற்கோ தகவல் தெரிவித்து ஆய்வு செய்ய வேண்டும்.',
      'documentsChecklistTitle': 'தேவையான ஆவணங்கள்',
      'doc1': '1. நில உரிமை ஆவணம் (பட்டா / சிட்டா / அடங்கல்)',
      'doc2': '2. ஆதார் கார்டு நகல்',
      'doc3': '3. சங்க உறுப்பினர் பாஸ்புக்',
      'doc4': '4. 2 பாஸ்போர்ட் அளவு புகைப்படங்கள் மற்றும் விண்ணப்பப் படிவம்',
      'step1': 'படி 1: வேலை நேரங்களில் (காலை 9 - மாலை 5) உள்ளூர் கூட்டுறவு சங்க செயலாளரை சந்திக்கவும்.',
      'step2': 'படி 2: பூர்த்தி செய்த விண்ணப்பத்துடன் ஆவணங்களைச் சமர்ப்பிக்கவும்.',
      'step3': 'படி 3: கண்காணிப்பிற்காக முத்திரையிடப்பட்ட ஒப்புதல் சீட்டைப் பெறவும்.',
      'help1': 'கூட்டுறவு சங்க செயலாளர் உதவி எண்: 1800-425-1090',
      'help2': 'மாவட்ட கூட்டுறவு துணைப் பதிவாளர் அலுவலகம்',
      'help3': 'புகார் தீர்வு காலம்: 15 நாட்கள் கட்டாய காலக்கெடு.',
    },
    'hi': {
      'appName': 'SarVani',
      'chooseLanguage': 'अपनी भाषा चुनें',
      'touchToBegin': 'प्रारंभ करने के लिए भाषा को छुएं',
      'askQuestion': 'अपना प्रश्न पूछें',
      'speakNaturally': 'अपनी मातृभाषा में सहजता से बोलें। कानूनी शब्दों की आवश्यकता नहीं है।',
      'tapToSpeak': 'बोलने के लिए दबाएं',
      'touchMicOrSpeak': 'माइक्रोफोन को छुएं या सहजता से बोलें',
      'listening': 'सुन रहा है…',
      'stop': 'रोकें',
      'sampleQuestionsTitle': 'नमूना प्रश्न:',
      'understandingQuestion': 'आपके प्रश्न को समझा जा रहा है...',
      'findingInformation': 'सही जानकारी खोजी जा रही है...',
      'backendRoute': 'बैकएंड मार्ग:',
      'yourAnswer': 'आपका उत्तर',
      'repeat': 'दोहराएं',
      'stopAudio': 'विराम',
      'askAnother': 'अन्य प्रश्न पूछें',
      'showDocuments': 'आवश्यक दस्तावेज़',
      'actionNextStepLabel': 'आगे के चरण',
      'getHumanHelp': 'सहायता / शिकायत जानकारी',
      'endSession': 'सत्र समाप्त करें',
      'reset': 'पुनः प्रारंभ',
      'q1_title': 'केसीसी कार्ड के लिए कौन से दस्तावेज़ चाहिए?',
      'q1_sub': 'केसीसी फसल ऋण आवेदन के लिए आवश्यक दस्तावेज़',
      'q2_title': 'मेरा केसीसी ऋण बकाया कितना है?',
      'q2_sub': 'ऋण खाता बकाया और देय तिथि की जांच करें',
      'q3_title': 'समिति में शिकायत कैसे दर्ज करें?',
      'q3_sub': 'समिति सचिव के पास शिकायत दर्ज करने की प्रक्रिया',
      'q_member_rights': 'सहकारी समिति के सदस्य के रूप में मेरे क्या अधिकार हैं?',
      'a_member_rights': 'एक पंजीकृत सहकारी सदस्य के रूप में, आपको समिति की खाता पुस्तकों, लेखा परीक्षा रिपोर्टों, सदस्यों की सूची और वार्षिक वित्तीय विवरणों का निरीक्षण करने का पूर्ण वैधानिक अधिकार है।',
      'q_crop_loan_docs': 'फसल ऋण आवेदन के लिए कौन से दस्तावेज़ आवश्यक हैं?',
      'a_crop_loan_docs': 'सहकारी समिति से फसल ऋण प्राप्त करने के लिए भूमि स्वामित्व रिकॉर्ड (पट्टा/खतौनी), आधार कार्ड, समिति सदस्यता पासबुक और आवेदन पत्र सह-संलग्न करना आवश्यक है।',
      'q_grievance': 'यदि सहकारी समिति रिकॉर्ड प्रदान नहीं करती है तो शिकायत कैसे करें?',
      'a_grievance': 'सर्वप्रथम समिति सचिव को लिखित आवेदन देकर पावती प्राप्त करें। 15 दिनों में समाधान न होने पर जिला उप-पंजीयक (सहकारिता) को औपचारिक शिकायत प्रस्तुत करें।',
      'q_crop_insurance': 'फसल बीमा दावे की प्रक्रिया और समय सीमा क्या है?',
      'a_crop_insurance': 'प्राकृतिक आपदा से फसल क्षति होने पर क्षति के 72 घंटे के भीतर समिति सचिव या फसल बीमा हेल्पलाइन को सूचित कर संयुक्त सर्वेक्षण कराना अनिवार्य है।',
      'documentsChecklistTitle': 'आवश्यक दस्तावेज़',
      'doc1': '1. भूमि स्वामित्व रिकॉर्ड (पट्टा / खतौनी)',
      'doc2': '2. आधार कार्ड की प्रति',
      'doc3': '3. समिति सदस्यता पासबुक',
      'doc4': '4. 2 पासपोर्ट आकार के फोटो एवं आवेदन पत्र',
      'step1': 'चरण 1: कार्य समय (सुबह 9 से शाम 5 बजे) के दौरान स्थानीय समिति सचिव से मिलें।',
      'step2': 'चरण 2: भरे हुए आवेदन पत्र के साथ दस्तावेज़ जमा करें।',
      'step3': 'चरण 3: ट्रैकिंग के लिए मुहर लगी पावती रसीद प्राप्त करें।',
      'help1': 'समिति सचिव हेल्पलाइन: 1800-425-1090',
      'help2': 'जिला उप-पंजीयक कार्यालय (सहकारिता)',
      'help3': 'शिकायत निवारण अवधि: 15 दिनों की सीमा।',
    },
    'te': {
      'appName': 'SarVani',
      'chooseLanguage': 'మీ భాషను ఎంచుకోండి',
      'touchToBegin': 'ప్రారంభించడానికి మీ భాషను తాకండి',
      'askQuestion': 'మీ ప్రశ్నను అడగండి',
      'speakNaturally': 'మీ భాషలో సహజంగా మాట్లాడండి.',
      'tapToSpeak': 'మాట్లాడటానికి నొక్కండి',
      'touchMicOrSpeak': 'మైక్రోఫోన్‌ను తాకి లేదా సహజంగా మాట్లాడండి',
      'listening': 'వింటోంది…',
      'stop': 'ఆపు',
      'sampleQuestionsTitle': 'నమూనా ప్రశ్నలు:',
      'understandingQuestion': 'మీ ప్రశ్నను అర్థం చేసుకుంటోంది...',
      'findingInformation': 'సరైన సమాచారాన్ని వెతుకుతోంది...',
      'backendRoute': 'సేవా మార్గం:',
      'yourAnswer': 'మీ సమాధానం',
      'repeat': 'మళ్లీ విను',
      'stopAudio': 'ఆపు',
      'askAnother': 'మరో ప్రశ్న అడగండి',
      'showDocuments': 'అవసరమైన పత్రాలు',
      'actionNextStepLabel': 'తదుపరి చర్యలు',
      'getHumanHelp': 'సహాయం / ఫిర్యాదు సమాచారం',
      'endSession': 'నిష్క్రమించు',
      'reset': 'రీసెట్',
      'q1_title': 'KCC కార్డ్ కోసం ఏ పత్రాలు కావాలి?',
      'q1_sub': 'KCC రుణ దరఖాస్తుకు అవసరమైన పత్రాలు',
      'q2_title': 'నా KCC రుణ బ్యాలెన్స్ ఎంత?',
      'q2_sub': 'రుణ ఖాతా బ్యాలెన్స్ మరియు గడువు తేదీని తనిఖీ చేయండి',
      'q3_title': 'సొసైటీలో ఫిర్యాదు చేయడం ఎలా?',
      'q3_sub': 'సొసైటీ కార్యదర్శికి ఫిర్యాదు చేసే విధానం',
      'q_member_rights': 'సహకార సభ్యునిగా నా హక్కులు ఏమిటి?',
      'a_member_rights': 'రిజిస్టర్డ్ సహకార సభ్యునిగా, సొసైటీ పుస్తకాలు, ఆడిట్ నివేదికలు మరియు వార్షిక ఆర్థిక ప్రకటనలను తనిఖీ చేసే చట్టబద్ధమైన హక్కు మీకు ఉంది.',
      'q_crop_loan_docs': 'పంట రుణం కోసం ఏ పత్రాలు అవసరం?',
      'a_crop_loan_docs': 'సహకార సొసైటీ నుండి పంట రుణం పొందడానికి భూమి హక్కు పత్రం (పట్టా), ఆధార్ కార్డ్, సొసైటీ పాస్‌బుక్ మరియు దరఖాస్తు ఫారమ్ సమర్పించాలి.',
      'q_grievance': 'సొసైటీ పత్రాలు ఇవ్వకపోతే ఫిర్యాదు చేయడం ఎలా?',
      'a_grievance': 'మొదట సొసైటీ కార్యదర్శికి లిఖితపూర్వకంగా దరఖాస్తు చేసి రసీదు పొందండి. 15 రోజుల్లో పరిష్కారం కాకపోతే జిల్లా డిప్యూటీ రిజిస్ట్రార్‌కు ఫిర్యాదు చేయవచ్చు.',
      'q_crop_insurance': 'పంట బీమా క్లెయిమ్ కాలపరిమితి ఎంత?',
      'a_crop_insurance': 'పంట నష్టం జరిగిన 72 గంటల్లో సొసైటీ కార్యదర్శికి లేదా బీమా హెల్ప్‌లైన్‌కు సమాచారం అందించాలి.',
      'documentsChecklistTitle': 'అవసరమైన పత్రాలు',
      'doc1': '1. భూమి హక్కు పత్రం (పట్టా/పహాణీ)',
      'doc2': '2. ఆధార్ కార్డ్ నకలు',
      'doc3': '3. సొసైటీ సభ్యత్వ పాస్‌బుక్',
      'doc4': '4. 2 పాస్‌పోర్ట్ సైజు ఫోటోలు మరియు దరఖాస్తు ఫారమ్',
      'step1': 'దశ 1: పని వేళల్లో స్థానిక సొసైటీ కార్యదర్శిని కలవండి.',
      'step2': 'దశ 2: పూర్తి చేసిన దరఖాస్తుతో పాటు పత్రాలను సమర్పించండి.',
      'step3': 'దశ 3: రసీదు పొందండి.',
      'help1': 'సొసైటీ కార్యదర్శి హెల్ప్‌లైన్: 1800-425-1090',
      'help2': 'జిల్లా సహకార డిప్యూటీ రిజిస్ట్రార్ కార్యాలయం',
      'help3': 'ఫిర్యాదు పరిష్కార సమయం: 15 రోజులు.',
    },
    'ml': {
      'appName': 'SarVani',
      'chooseLanguage': 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
      'touchToBegin': 'തുടങ്ങാൻ ഭാഷയിൽ തൊടുക',
      'askQuestion': 'നിങ്ങളുടെ ചോദ്യം ചോദിക്കുക',
      'speakNaturally': 'നിങ്ങളുടെ മാതൃഭാഷയിൽ സംസാരിക്കുക.',
      'tapToSpeak': 'സംസാരിക്കാൻ അമർത്തുക',
      'touchMicOrSpeak': 'മൈക്രോഫോണിൽ തൊടുക അല്ലെങ്കിൽ സംസാരിക്കുക',
      'listening': 'കേൾക്കുന്നു…',
      'stop': 'നിർത്തുക',
      'sampleQuestionsTitle': 'മാതൃകാ ചോദ്യങ്ങൾ:',
      'understandingQuestion': 'ചോദ്യം മനസ്സിലാക്കുന്നു...',
      'findingInformation': 'വിവരങ്ങൾ കണ്ടെത്തുന്നു...',
      'backendRoute': 'സേവന മാർഗ്ഗം:',
      'yourAnswer': 'നിങ്ങളുടെ മറുപടി',
      'repeat': 'വീണ്ടും കേൾക്കുക',
      'stopAudio': 'നിർത്തുക',
      'askAnother': 'മറ്റൊരു ചോദ്യം ചോദിക്കുക',
      'showDocuments': 'ആവശ്യമുള്ള രേഖകൾ',
      'actionNextStepLabel': 'അടുത്ത നടപടികൾ',
      'getHumanHelp': 'സഹായം / പരാതി വിവരങ്ങൾ',
      'endSession': 'പുറത്തുകടക്കുക',
      'reset': 'റീസെറ്റ്',
      'q1_title': 'KCC കാർഡിന് എന്തൊക്കെ രേഖകൾ വേണം?',
      'q1_sub': 'KCC വായ്പയ്ക്ക് ആവശ്യമായ രേഖകൾ',
      'q2_title': 'എന്റെ KCC വായ്പാ കുടിശ്ശിക എത്രയാണ്?',
      'q2_sub': 'വായ്പാ അക്കൗണ്ട് വിവരങ്ങൾ പരിശോധിക്കുക',
      'q3_title': 'സൊസൈറ്റിയിൽ എങ്ങനെ പരാതിപ്പെടാം?',
      'q3_sub': 'സൊസൈറ്റി സെക്രട്ടറിക്ക് പരാതി നൽകുന്ന രീതി',
      'q_member_rights': 'സഹകരണ സംഘാംഗം എന്ന നിലയിൽ എന്റെ അവകാശങ്ങൾ എന്തൊക്കെയാണ്?',
      'a_member_rights': 'അംഗമായ സഹകാരിക്ക് സൊസൈറ്റി അക്കൗണ്ടുകളും ഓഡിറ്റ് റിപ്പോർട്ടുകളും പരിശോധിക്കാൻ നിയമപരമായ അവകാശമുണ്ട്.',
      'q_crop_loan_docs': 'വായ്പയ്ക്കായി എന്തൊക്കെ രേഖകൾ വേണം?',
      'a_crop_loan_docs': 'കർഷക വായ്പയ്ക്ക് ഭൂമിയുടെ അവകാശ രേഖ, ആധാർ കാർഡ്, പാസ്ബുക്ക് എന്നിവ സമർപ്പിക്കണം.',
      'q_grievance': 'സൊസൈറ്റി രേഖകൾ നൽകിയില്ലെങ്കിൽ എങ്ങനെ പരാതിപ്പെടാം?',
      'a_grievance': 'സൊസൈറ്റി സെക്രട്ടറിക്ക് രേഖാമൂലം അപേക്ഷ നൽകി രസീത് വാങ്ങുക. 15 ദിവസത്തിനകം പരിഹാരമുണ്ടായില്ലെങ്കിൽ രജിസ്ട്രാർക്ക് പരാതി നൽകാം.',
      'q_crop_insurance': 'വിള ഇൻഷുറൻസ് ആനുകൂല്യം ലഭിക്കാനുള്ള സമയപരിധി എത്രയാണ്?',
      'a_crop_insurance': 'കൃഷിനാശം സംഭവിച്ചാൽ 72 മണിക്കൂറിനകം വിവരമറിയിക്കേണ്ടതാണ്.',
      'documentsChecklistTitle': 'ആവശ്യമുള്ള രേഖകൾ',
      'doc1': '1. ഭൂമി കൈവശാവകാശ രേഖ',
      'doc2': '2. ആധാർ കാർഡ് കോപ്പി',
      'doc3': '3. അംഗത്വ പാസ്ബുക്ക്',
      'doc4': '4. 2 ഫോട്ടോയും അപേക്ഷാ ഫോമും',
      'step1': 'ഘട്ടം 1: സൊസൈറ്റി സെക്രട്ടറിയെ കാണുക.',
      'step2': 'ഘട്ടം 2: അപേക്ഷയും രേഖകളും സമർപ്പിക്കുക.',
      'step3': 'ഘട്ടം 3: രസീത് കൈപ്പറ്റുക.',
      'help1': 'സൊസൈറ്റി ഹെൽപ്പ് ലൈൻ: 1800-425-1090',
      'help2': 'ജില്ലാ സഹകരണ ഡെപ്യൂട്ടി രജിസ്ട്രാർ ഓഫീസ്',
      'help3': 'പരാതി പരിഹാര സമയം: 15 ദിവസം.',
    },
    'kn': {
      'appName': 'SarVani',
      'chooseLanguage': 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'touchToBegin': 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಸ್ಪರ್ಶಿಸಿ',
      'askQuestion': 'ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ',
      'speakNaturally': 'ನಿಮ್ಮ ಆಯ್ಕೆಯ ಭಾಷೆಯಲ್ಲಿ ಸಹಜವಾಗಿ ಮಾತನಾಡಿ.',
      'tapToSpeak': 'ಮಾತನಾಡಲು ಸ್ಪರ್ಶಿಸಿ',
      'touchMicOrSpeak': 'ಮೈಕ್ರೋಫೋನ್ ಸ್ಪರ್ಶಿಸಿ ಅಥವಾ ಸಹಜವಾಗಿ ಮಾತನಾಡಿ',
      'listening': 'ಆಲಿಸಲಾಗುತ್ತಿದೆ…',
      'stop': 'ನಿಲ್ಲಿಸಿ',
      'sampleQuestionsTitle': 'ಮಾದರಿ ಪ್ರಶ್ನೆಗಳು:',
      'understandingQuestion': 'ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಅರ್ಥೈಸಿಕೊಳ್ಳಲಾಗುತ್ತಿದೆ...',
      'findingInformation': 'ಸರಿಯಾದ ಮಾಹಿತಿಯನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...',
      'backendRoute': 'ಸೇವಾ ಮಾರ್ಗ:',
      'yourAnswer': 'ನಿಮ್ಮ ಉತ್ತರ',
      'repeat': 'ಮತ್ತೊಮ್ಮೆ ಕೇಳಿ',
      'stopAudio': 'ನಿಲ್ಲಿಸಿ',
      'askAnother': 'ಮತ್ತೊಂದು ಪ್ರಶ್ನೆ ಕೇಳಿ',
      'showDocuments': 'ಅಗತ್ಯ ದಾಖಲೆಗಳು',
      'actionNextStepLabel': 'ಮುಂದಿನ ಹಂತಗಳು',
      'getHumanHelp': 'ಸಹಾಯ / ದೂರು ಮಾಹಿತಿ',
      'endSession': 'ನಿರ್ಗಮನ',
      'reset': 'ಮರುಹೊಂದಿಸಿ',
      'q1_title': 'KCC ಕಾರ್ಡ್‌ಗೆ ಯಾವ ದಾಖಲೆಗಳು ಬೇಕು?',
      'q1_sub': 'KCC ಸಾಲದ ಅರ್ಜಿಗೆ ಅಗತ್ಯವಿರುವ ದಾಖಲೆಗಳು',
      'q2_title': 'ನನ್ನ KCC ಸಾಲದ ಬಾಕಿ ಎಷ್ಟಿದೆ?',
      'q2_sub': 'ಸಾಲದ ಖಾತೆ ಬಾಕಿ ಮತ್ತು ಗಡುವು ದಿನಾಂಕ ಪರೀಕ್ಷಿಸಿ',
      'q3_title': 'ಸಂಘದಲ್ಲಿ ದೂರು ನೀಡುವುದು ಹೇಗೆ?',
      'q3_sub': 'ಸಂಘದ ಕಾರ್ಯದರ್ಶಿಗೆ ದೂರು ಸಲ್ಲಿಸುವ విధాన',
      'q_member_rights': 'ಸಹಕಾರ ಸಂಘದ ಸದಸ್ಯರಾಗಿ ನನ್ನ ಹಕ್ಕುಗಳು ಯಾವುವು?',
      'a_member_rights': 'ನೊಂದಾಯಿತ ಸಹಕಾರ ಸದಸ್ಯರಾಗಿ, ಸಂಘದ ಲೆಕ್ಕಪತ್ರಗಳು ಮತ್ತು ವಾರ್ಷಿಕ ಆರ್ಥಿಕ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಲು ನಿಮಗೆ ಕಾನೂನುಬದ್ಧ ಹಕ್ಕಿದೆ.',
      'q_crop_loan_docs': 'KCC ಕಾರ್ಡ್ ಅಥವಾ ಬೆಳೆ ಸಾಲಕ್ಕೆ ಯಾವ ದಾಖಲೆಗಳು ಬೇಕು?',
      'a_crop_loan_docs': 'ಸಹಕಾರ ಸಂಘದಿಂದ ಬೆಳೆ ಸಾಲ ಅಥವಾ KCC ಕಾರ್ಡ್ ಪಡೆಯಲು ಭೂಮಿ ಹಕ್ಕು ದಾಖಲೆ (ಪಟಾ/ಪಹಣಿ), ಆಧಾರ್ ಕಾರ್ಡ್, ಸದಸ್ಯತ್ವ ಪಾಸ್‌ಬುಕ್ ಮತ್ತು ಅರ್ಜಿ ನಮೂನೆ ಸಲ್ಲಿಸಬೇಕು.',
      'q_grievance': 'ಸಹಕಾರ ಸಂಘ ದಾಖಲೆಗಳನ್ನು ನೀಡದಿದ್ದರೆ ದೂರು ನೀಡುವುದು ಹೇಗೆ?',
      'a_grievance': 'ಮೊದಲು ಸಂಘದ ಕಾರ್ಯದರ್ಶಿಗೆ ಲಿಖಿತ ಅರ್ಜಿ ನೀಡಿ ಸ್ವೀಕೃತಿ ಪಡೆಯಿರಿ. 15 ದಿನಗಳಲ್ಲಿ ಪರಿಹಾರ ಸಿಗದಿದ್ದರೆ ಉಪ ನಿಬಂಧಕರಿಗೆ ದೂರು ಸಲ್ಲಿಸಬಹುದು.',
      'q_crop_insurance': 'ಬೆಳೆ ವಿಮೆ দাবি സമയപരിധി ಎಷ್ಟು?',
      'a_crop_insurance': 'ಬೆಳೆ ಹಾನಿಯಾದ 72 ಗಂಟೆಗಳ ಒಳಗೆ ಸಂಘದ ಕಾರ್ಯದರ್ಶಿಗೆ ತಿಳಿಸಬೇಕು.',
      'documentsChecklistTitle': 'ಅಗತ್ಯ ದಾಖಲೆಗಳು',
      'doc1': '1. ಭೂಮಿ ಹಕ್ಕು ದಾಖಲೆ (ಪಟಾ/ಪಹಣಿ)',
      'doc2': '2. ಆಧಾರ್ ಕಾರ್ಡ್ ಪ್ರತಿ',
      'doc3': '3. ಸದಸ್ಯತ್ವ ಪಾಸ್‌ಬುಕ್',
      'doc4': '4. 2 ಫೋಟೋ ಮತ್ತು ಅರ್ಜಿ ನಮೂನೆ',
      'step1': 'ಹಂತ 1: ಸಂಘದ ಕಾರ್ಯದರ್ಶಿಯನ್ನು ಭೇಟಿ ಮಾಡಿ.',
      'step2': 'ಹಂತ 2: ಭರ್ತಿ ಮಾಡಿದ ಅರ್ಜಿಯೊಂದಿಗೆ ದಾಖಲೆಗಳನ್ನು ಸಲ್ಲಿಸಿ.',
      'step3': 'ಹಂತ 3: ಸ್ವೀಕೃತಿ ರಸೀದಿ ಪಡೆಯಿರಿ.',
      'help1': 'ಸಹಾಯವಾಣಿ: 1800-425-1090',
      'help2': 'ಜಿಲ್ಲಾ ಸಹಕಾರ ಉಪ ನಿಬಂಧಕರ ಕಚೇರಿ',
      'help3': 'ದೂರು ಪರಿಹಾರ ಅವಧಿ: 15 ದಿನಗಳು.',
    },
  };

  String getText(String key) {
    return _localizedValues[langCode]?[key] ?? _localizedValues['en']![key] ?? key;
  }
}
